import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import Fullpage, {FullPageSections, FullpageSection, FullpageNavigation} from '@ap.cx/react-fullpage'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Fullpage>
        <FullpageNavigation />
        <FullPageSections>

          <FullpageSection className={'section'}>
            <div>
              Screen 1
            </div>
          </FullpageSection>

          <FullpageSection className='section'>
            <div>
              Screen 2
            </div>
          </FullpageSection>

        </FullPageSections>
      </Fullpage>
    </div>
  )
  
}
